### ISSUE TITLE
[RFC] Use mipmap filtering in window thumbnails

### ISSUE THREAD

**Issue by Mel34** [polaur/repo-refreshed#11]
Please take a look at [this](https://github.com/Mel34/plasma-frameworks) and let me know what you think. 

If you're interested, you have my OK to merge it.

**Comment by worldofpeace** [comment]
@Mel34 We're kind of ifffy on including lots of 'artistic' changes in repo-refreshed. 
@pavbaranov intends for this repo to be mostly bugfixes and maybe some features that are reasonable and tested.

I really like the changes happening in phabricator, and I think there would be a purpose for a repo that really just showcases all these pretty changes for the testing community to try on arch linux.

**Comment by Mel34** [comment]
Let me know if you decide to start such a showcase repo. I would be interested in contributing to it, if you keep it in sync with this repo. Ideally, I want both eye candy and bugfixes.

Also, regarding this feature, it's been accepted on phabricator, but they haven't landed a commit yet. I understand what you're saying though, it's a good policy to run a repo.

Thanks for consideration.

**Comment by worldofpeace** [comment]
> Also, regarding this feature, it's been accepted on phabricator, but they haven't landed a commit yet.

We're actually ok with having unmerged features.
> Let me know if you decide to start such a showcase repo. I would be interested in contributing to it, if you keep it in sync with this repo. Ideally, I want both eye candy and bugfixes.

We'll see what happens later in the week I suppose :)

I'll most likely be using your [plasma frameworks](https://github.com/Mel34/plasma-frameworks)
despite this :+1: Thanks!

**Comment by pavbaranov** [comment]
Calm down everybody :)
Let me explain something.
Of course we can do something completly experimental. But... Is there any sense of that? Phabricator works sometimes are merged to main repository (I mean KDE's anongit) and after a while those commits are removed because of something. 
This repository is for every user who want to have packages with (mostly) bugifixes earlier then in official repository or even in official stable or unstable branches in KDE. But... calm down we cannot give users PKGBUILDs with completly untested patches.
KDE Frameworks is base for almost all KDE packages and even more. We cannot do any untested changes in it. Of course, where is some bugfixes we can and should applied those bugfix patches, but not those, that makes KDE more "beautiful" but maybe are destrictive in other places. New version of KF5 are every second saturday of each month. We have special repository for RC version. 
So, calm down, and be patient.
